---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-clippy
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-premium